# SPDX-FileCopyrightText: 2006-2025, Knut Reinert & Freie Universität Berlin
# SPDX-FileCopyrightText: 2016-2025, Knut Reinert & MPI für molekulare Genetik
# SPDX-License-Identifier: CC0-1.0

name: Header

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

concurrency:
  group: misc-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name != 'push' }}

env:
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -Eexuo pipefail {0}

jobs:
  build:
    name: ${{ matrix.compiler }}
    runs-on: ubuntu-latest
    if: github.repository_owner == 'seqan' || github.event_name == 'workflow_dispatch'
    strategy:
      fail-fast: false
      matrix:
        compiler: ["clang-latest", "clang-third-latest", "gcc-latest", "gcc-third-latest"]
    container:
      image: ghcr.io/seqan/${{ matrix.compiler }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup cache
        uses: seqan/actions/setup-actions-cache@main

      - name: Configure tests
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Debug \
                   -DDREAM-STELLAR_HEADER_TEST_ONLY=ON
          make gtest_main

      - name: Build tests
        working-directory: build
        run: |
          ccache -z
          make -k
          ccache -sv

      - name: Run tests
        working-directory: build
        run: ctest . -j --output-on-failure --no-tests=error
